flake.lock, flake.nix
- Remove `flake-utils`
- Limit supported platforms to linux
- Export `packages.${system}.default`
=> feat(nix): export default package

examples/bar/config.py, ignis/utils/poll.py
Correct `Utils.Poll()` timeout value use second instead of millisecond.
=> Fix poll example

ignis/services/notifications/service.py
Fix set_popup_timeout function by adding `.value`
```python
@popup_timeout.setter
def popup_timeout(self, value: int) -> None:
self._popup_timeout_opt.value = value
```
=> Fix set_popup_timeout function

docs/user/faq.rst, ignis/app.py
=> feat: IgnisApp.add_icons()

ignis/services/upower/constants.py, ignis/services/upower/device.py
Fixing a bug where UPower charging and charged state always return False
=> fix: UPower Device State always return false

ignis/services/network/vpn.py
Adds wireguard to the filter for vpn connections.
=> feat(network): support wireguard vpn connections

ignis/services/system_tray/item.py
=> fix: use the icon provided by a Spotify installation when it is unavailable in the icon theme

ignis/services/fetch/service.py
adds a simple module to the fetch service to return the cpu temperature as a float.
=> feat: add cpu_temp to fetch service

ignis/widgets/eventbox.py
This PR adds support for right & left scroll events on EventBox widgets.
=> Feat(Widget.EventBox): Add support for right & left scroll events

ignis/services/network/access_point.py, ignis/services/network/util.py, ignis/services/network/wifi_connect_dialog.py
=> fix(network): WifiConnectDialog: use an unique window name based on the bssid

docs/examples/code_snippets.rst, docs/examples/configurations.rst, docs/examples/index.rst
=> docs: add Code Snippets to examples

ignis/services/applications/application.py
=> feat(applications): add `Application.launch_uwsm()`

ignis/widgets/popover_menu.py
=> refactor(`Widget.PopoverMenu`): improve menu generation logic

ignis/cli.py, ignis/logging.py
=> feat: follow XDG base directories

docs/api/utils/file.rst, ignis/utils/__init__.py, ignis/utils/file.py
This PR adds 4 new functions to ``Utils``, based on ``Gio``.
- ``read_file()``
- ``read_file_async()``
- ``write_file()``
- ``write_file_async()``
=> feat(utils): add functions for file operations

dev.txt, docs/api/utils/misc.rst, docs/conf.py, docs/user/installation.rst, examples/bar/README.md, ignis/services/mpris/player.py, ignis/utils/__init__.py, ignis/utils/download_image.py, nix/ignis.nix, pyproject.toml, requirements.txt
Reverts linkfrg/ignis#150
I think I was a little hasty. I noticed some bugs (right after I merged it 👍👍👍).
In case of a clean start of Ignis and the first launch of any player, the player in the control center (from my dotfiles) may appear and... immediately disappear. Or it may have wrong colors, for example the player icon is red and everything else is blue.
It's just magic, I still can't find the cause of the problem, so I'm reverting to fix it.
=> Revert "refactor!(`MprisPlayer`): move to asynchronous property synchronization"

ignis/services/mpris/player.py, ignis/services/mpris/util.py
#150, but in asyncio style and with bug fixes
``Utils.download_image()`` will be removed in separate commits
=> refactor(`MprisPlayer`): move to asynchronous property synchronization

docs/api/utils/icon.rst, ignis/utils/__init__.py, ignis/utils/icon.py
=> feat: add `Utils.get_app_icon_name()`

ignis/utils/shell.py
=> fix(`Utils.exec_sh_async`): use asyncio for creating subprocess instead of Gio

flake.nix, meson.build, meson_options.txt, nix/ignis.nix, nix/overlay.nix
=> fix(nix): include build commit hash using `self.rev`

ignis/__init__.py, ignis/gobject.py
=> fix: resolve compatibility issues with PyGObject 3.52.0 (girepository 2.0)

ignis/services/hyprland/service.py, ignis/services/hyprland/window.py
=> feat(`HyprlandService`): add `windows` property

docs/api/options_manager.rst, ignis/options_manager.py
Preparation for #199. This PR adds a new `TrackedList` class which will replace regular python list in Options.
=> feat(`OptionsManager`): implement `TrackedList`

ignis/options.py, ignis/services/applications/application.py, ignis/services/applications/service.py
=> feat: support modifying `options.applications.pinned_apps`

docs/api/services/hyprland.rst, ignis/services/hyprland/__init__.py, ignis/services/hyprland/monitor.py, ignis/services/hyprland/service.py
=> feat(`HyprlandService`): add `monitors` property

ignis/services/system_tray/service.py
Fixes regression caused by 6ba969e7f865cfbce583bfd93f7b8c35d89f367b.
``__initialize_item()`` is launched as a task (we can say in the background) which asynchronously initializes an item and adds it to `_items`. It takes some time to initialize an item, and then LocalSend makes the second `RegisterStatusNotifierItem`, but the previous item is still initializing and is not added to `_items`, so `if bus_name in self._items` check doesn't work.
Closes: #221
=> fix(`SystemTrayService`): do not init item if another task with the same bus name is already running

ignis/services/hyprland/service.py
=> fix(`HyprlandService`): do not add object if its data is empty

ignis/app.py
=> fix(`IgnisApp`): inherit parameters passed to `apply_css()` in `reload_css()`

ignis/app.py
=> fix(nix): directly use the Ignis executable on reload

ignis/services/hyprland/service.py
=> feat(`HyprlandService`): support `moveworkspace` event

ignis/widgets/window.py
=> fix(`Window`): improve handling of size changes for `dynamic_input_region`

ignis/utils/file.py
This small PR raises a `TypeError` exception in `ignis/utils/file.py`.
=> fix(`utils/file`): raise `TypeError` exceptions

docs/conf.py, docs/requirements.txt, docs/user/cli.rst, docs/user/installation.rst, ignis/cli.py, ignis/main.py, nix/default.nix, pyproject.toml, requirements.txt
This reverts commit 12c41f5b461b7cfd9cad5b50423620849c6e5b9c.
Reason: #295
=> Revert "feat!(cli): move to `typer` (#277)"

ignis/cli.py
BREAKING CHANGE: some commands renamed:
* `open` -> `open-window`
* `close` -> `close-window`
* `toggle` -> `toggle-window`
=> feat!(cli): small improvements to CLI messages & command names

ignis/app.py
=> fix: remove temp dir on quit

ignis/widgets/regular_window.py
=> fix(docs): fix RegularWindow docs typo

nix/hm-module-doc.md, nix/hm-module.nix
=> feat(nix): add `finalPackage` HM option

docs/user/nix.rst, flake.nix, nix/default.nix, nix/hm-module.nix
=> nix: manage optional dependencies in `default.nix`

ignis/widgets/button.py, ignis/widgets/eventbox.py
Current version allows setting on_click/on_right_click/on_middle_click, but doesn't change the gesture handler itself.
on_hover/scroll_* handlers in eventbox already are dynamic, so this change will bring consistency. 
Maybe some form of constant handler will be better than an inner function?
=> fix(`Button` & `EventBox`): refer to the new callback in click handlers

docs/api/widgets/Fixed.rst, ignis/widgets/__init__.py, ignis/widgets/fixed.py
Implementation:
https://github.com/user-attachments/assets/62296e87-1bb3-4b14-ae95-6a64f0526a64
https://github.com/user-attachments/assets/712443ea-e09a-4fe2-9fda-345f013c6160
Would be great if we can have a animation decorator just like debounce
=> feat: add `Fixed` widget
