- docs/user/installation.rst
- nix/ignis.nix
By copying the submodule source during nix build,
remove the required submodule checkout introduced by https://github.com/linkfrg/ignis/pull/25.
> feat(nix): remove submodules for nix build

- nix/ignis.nix
Currently the recorder service is not working (atleast for me), because python bindings for GStreamer are not included in  build-inputs. so this commit adds that
> fix(nix): add GStreamer & PipeWire to build inputs

- nix/ignis.nix
Change the `wrapProgram` invocation to use `--prefix-each` instead of `--set` to allow inheriting the `PATH` environment variable from the system. This ensures `/run/current-system/sw/bin`, etc. are included in the PATH, allowing `Utils.exec_sh` to execute binaries installed on the system.
Fixes #70
> fix(nix): prefix PATH instead of overwriting it

- nix/ignis.nix
The default pixbuf module loader cache does not have any loader registered for SVG files and causes nearly all icon themes to stop working or have a tiny subset of their icons. This was fixed by using the loader cache provided by the librsvg package which contains an entry for SVG images pointing to its internal pixbuf loader.
Fixes #77
> fix(nix): use librsvg pixbuf module loader cache to allow loading SVG icons

- ignis/services/network/__init__.py
- ignis/services/network/access_point.py
- ignis/services/network/ethernet.py
- ignis/services/network/ethernet_device.py
- ignis/services/network/util.py
- ignis/services/network/vpn.py
- ignis/services/network/wifi.py
- ignis/services/network/wifi_device.py
- stubs/gi/repository/NM.pyi
This PR refactors signals handling in the Network Service.
Now components of the Network Service rely on such signals like ``device-added`` / ``device-removed`` (NM.Client) and etc.
It makes code easier and less shitty.
But the main goal is to provide new signals, you can find them in the code with descriptions in docstrings.
Closes: #50
> feat(network): refactor signal handling

- ignis/services/network/access_point.py
This PR removes the ``WifiAccessPoint.is_connected`` property and adds the ``security`` property instead, which is now used in ``connect_to_graphical()`` method
Closes: #83
> fix(network): use rsn_flags & wpa_flags to check the security protocol of an access point

- nix/ignis.nix
I think the bluetooth service is added to ignis without updating the corresponding dependencies in the nix file as well.
> fix(nix): add `gnome-bluetooth` to `GI_TYPELIB_PATH`

- docs/api/widgets/Stack.rst
- ignis/widgets/__init__.py
- ignis/widgets/stack.py
- ignis/widgets/stack_page.py
- ignis/widgets/stack_switcher.py
Example usage:
```python
from ignis.widgets import Widget
stack = Widget.Stack(
child=[
Widget.StackPage(
title="page 1", child=Widget.Label(label="welcome to page 1!")
),
Widget.StackPage(
title="page 2", child=Widget.Label(label="welcome to page 2!")
),
Widget.StackPage(
title="page 3", child=Widget.Label(label="welcome to page 3!")
),
]
)
Widget.Box(
vertical=True,
child=[Widget.StackSwitcher(stack=stack), stack],
)
```
Closes: #71
> feat: add `Widget.Stack` (`Widget.StackPage`, `Widget.StackSwitcher`)

- ignis/services/system_tray/item.py
I issued about spotify icon before https://github.com/linkfrg/ignis/issues/61
It got fixed in Arch. But It didn't get fixed in NixOS or spotify-launcher in Arch. Since it was using absolute path, it coudn't fix it. So I added this to fix it...
> fix(tray): add icon theme of item to search path

- ignis/app.py
- ignis/exceptions.py
- ignis/utils/sass.py
This adds support for an alternate Sass compiler using import-time detection, and also fixes a failure to find sass if it's in a weird location (but still in PATH).
I'm packaging Ignis for Gentoo and this was easier than bringing in the Dart ecosystem, which, turns out, is completely missing on Gentoo.
> feat: support Grass Sass compiler as a fallback

- nix/ignis.nix
/bin/sass does not match on anything anymore and makes the build fail.
> fix: nix build

- ignis/client.py
- ignis/dbus.py
- ignis/dbus_menu.py
- ignis/services/backlight/device.py
- ignis/services/backlight/util.py
- ignis/services/mpris/player.py
- ignis/services/mpris/service.py
- ignis/services/notifications/service.py
- ignis/services/recorder/session.py
- ignis/services/system_tray/item.py
- ignis/services/system_tray/service.py
- ignis/services/systemd/service.py
- ignis/services/systemd/unit.py
- ignis/services/upower/device.py
- ignis/services/upower/service.py
This PR brings two new methods to `DBusProxy`: `new` and `new_async` to replace the standard ``__init__``.
``__init__`` still can be used, but now it requires different arguments: `bus_type` and `gproxy`.
> refactor!: overhaul `DBusProxy` initialization & add support for async initialization

- .github/ISSUE_TEMPLATE/1-bug.yaml
- ignis/cli.py
- ignis/logging.py
This PR brings support for XDG Base Directories instead of hard-coded paths like `~/.config/ignis`.
There is also a little breaking change: logs now stored at `$XDG_STATE_HOME/ignis/ignis.log` (`~/.local/state/ignis/ignis.log`).
Closes: #143
> feat!: follow XDG base directories

- ignis/services/system_tray/item.py
This PR brings asynchronous D-Bus property synchronization to `SystemTrayItem`.
This will affect mainly internal stuff.
Public API remains the same, except for a small changes in property type hints.
Some of them can be ``None``.
Closes: #140
> fix(`SystemTrayItem`): move to asynchronous property synchronization

- docs/requirements.txt
Workaround for tox-dev/sphinx-autodoc-typehints#523
> docs: pin sphinx version to 8.1.0

- docs/user/async.rst
- docs/user/index.rst
- docs/user/installation.rst
- examples/bar/config.py
- ignis/__init__.py
- ignis/dbus.py
- ignis/services/bluetooth/device.py
- ignis/services/network/access_point.py
- ignis/services/network/ethernet_device.py
- ignis/services/network/vpn.py
- ignis/services/network/wifi_connect_dialog.py
- ignis/services/network/wifi_device.py
- ignis/services/system_tray/item.py
- ignis/utils/exec_sh.py
- ignis/utils/file.py
- ignis/widgets/file_chooser_button.py
- ignis/widgets/file_dialog.py
- pyproject.toml
- requirements.txt
PyGObject 3.50.0 introduces asyncio integration with support to await Gio async functions.
This makes working with Gio's asynchronous functions much easier by providing a convenient pythonic API.
This PR is aimed at adding integration with asyncio and rewriting async stuff to the asyncio style.
Affected (public) functions:
- DBusProxy
- new_async()
- get_dbus_property_async()
- set_dbus_property_async()
- BluetoothDevice
- connect_to()
- disconnect_from()
- WifiAccessPoint
- commit_changes_async()
- connect_to()
- connect_to_graphical()
- disconnect_from()
- forget()
- EthernetDevice
- connect_to()
- disconnect_from()
- VpnConnection
- connect_to()
- disconnect_from()
- WifiDevice
- scan()
- Utils.exec_sh_async()
- Utils.read_file_async()
- Utils.write_file_async()
- …
> feat!: asyncio integration

- docs/api/connection_manager.rst
- docs/api/index.rst
- ignis/connection_manager.py
This PR brings two new classes:  `ConnectionManager` and `DBusConnectionManager`.
They are intended to help with managing handler IDs to simplify bulk disconnection from signals.
It will later be used to disconnect from GObject and D-Bus signals gracefully, preventing from unwanted callbacks calls.
> feat: add `ConnectionManager` & `DBusConnectionManager`

- ignis/widgets/revealer_window.py
> fix(`RevealerWindow`): do not set `Revealer` as the child in the `revealer` setter

- docs/api/services/hyprland.rst
- ignis/services/hyprland/__init__.py
- ignis/services/hyprland/_object.py
- ignis/services/hyprland/keyboard.py
- ignis/services/hyprland/service.py
- ignis/services/hyprland/window.py
- ignis/services/hyprland/workspace.py
This PR brings objects inherited from ``IgnisGObject`` for Hyprland Service, replacing usual python dictionaries.
This approach allows to bind to properties and other GObject features.
New classes:
- ``HyprlandWorkspace``
- ``HyprlandWindow``
- ``HyprlandKeyboard``
Migration Guide:
1. Since these objects are not dictionaries anymore, you have to get properties like usual class attributes:
```python
hyprland.active_workspace["id"]
hyprland.active_workspace.id
```
2. ``HyprlandService.kb_layout`` is removed, use ``HyprlandService.main_keyboard.active_keymap`` instead.
3. ``HyprlandService.switch_kb_layout()`` is removed, use ``HyprlandService.main_keyboard.switch_layout()`` instead (to restore the old functionality pass ``"next"`` as an argument to it).
4. ``HyprlandService.workspaces`` …
> feat!(`HyprlandService`): move to GObject-based objects

- ignis/services/mpris/player.py
> fix(`MprisPlayer`): do not sync position if playback status is ``"Paused"``

- ignis/services/hyprland/_object.py
> fix(`HyprlandService`): check for presence of attribute when syncing object properties

- ignis/widgets/box.py
Closes: #179
This PR dynamically replaces the ``unparent()`` function of a Widget.Box child with the wrapper that additionally removes that child using ``Widget.Box.remove()`` method.
> fix(`Widget.Box`): remove child on unparent

- ignis/services/backlight/device.py
- ignis/services/backlight/service.py
- ignis/services/mpris/player.py
- ignis/services/system_tray/item.py
- ignis/services/systemd/unit.py
Many services with public functions that call D-Bus methods did so asynchronously using ``result_handler *args: None``.
This made these functions asynchronous but did not allow passing a custom result handler, nor did it follow the async/await style.
This PR adds explicit async versions of these methods. The current ones are now synchronous.
Affected methods:
- ``MprisPlayer``
- ``next()``
- ``previous()``
- ``pause()``
- ``play()``
- `play_pause()`
- `stop()`
- `seek()`
- `SystemTrayItem`
- `activate()`
- `secondary_activate()`
- `context_menu()`
- `scroll()`
- `SystemdUnit`
- `start()`
- `stop()`
- `restart()`
This also affects some property setters:
``BacklightDevice.brightness`` setter is now synchronous, you can use its asynchronous version which is available as usual method: …
> feat!: add explicit async versions of D-Bus methods for services

- ignis/services/fetch/service.py
Currently `FetchService.cpu_temp()` only works for CPUs that use the [`x86_pkg_temp_thermal` driver](https://www.kernel.org/doc/html/latest/driver-api/thermal/x86_pkg_temperature_thermal.html), which is used by various Intel CPUs.
This adds support for CPUs that rely on the [`k10temp` driver](https://www.kernel.org/doc/html/latest/hwmon/k10temp.html), namely, various AMD CPUS.
I also factored the code for checking both kinds into their own private functions that get called by `cpu_temp()` so the distinction is clearer and for ease of maintenance if support for other temperature drivers is added.
The practical difference as far as I am aware is pretty much just that they expose temperature information in files in different system directories, which have different structures.
I do not own …
> feat: add k10temp cpu temperature support to fetch service

- ignis/utils/sass.py
Avoid store the compiled CSS file in a hard-coded path.
This will prevent the file being overwritten when running multiple instances (https://github.com/linkfrg/ignis/issues/137).
> feat: store compiled css file in a random temporary directory

- ignis/services/hyprland/service.py
Parse `event_data` into pair, in case `event_value` containing `>>`.
> fix(HyprlandService): parse event data correctly with multiple ">>"

- ignis/services/hyprland/service.py
`get_monitor_name` -> `get_monitor_by_name`
> fix!(`HyprlandService`): rename method to match return type

- ignis/__init__.py
- ignis/options.py
- ignis/options_manager.py
This PR makes `Options` to store its data in `$XDG_DATA_HOME/ignis/options.json` (`$HOME/.local/share/ignis/options.json`) instead of `$XDG_CACHE_HOME/ignis/ignis_options.json`.
Also it adds `ignis.DATA_DIR` variable.
This change will protect options from being removed when the user clears cache.
`Options` will automatically migrate your options from the old file to the new one.
Consider migrating your user options (if you use them) to the new directory (e.g., `f"{DATA_DIR}/user_options.json"`.
> feat!: store options in `XDG_DATA_HOME`

- ignis/widgets/listbox.py
Previously `select_row()` triggered the row activation too. Actually it's not correct behavior. 
Now `select_row()` will only visually highlight the row. To activate a row manually, use the new `activate_row()` method instead.
Closes: #241
> fix!(`ListBox`): do not activate row on `select_row()`

- ignis/cli.py
This PR adds support for relative file paths for `ignis init` and `ignis run-file` CLI commands.
Closes: #242
> feat(cli): support relative file paths

- docs/conf.py
- docs/requirements.txt
- docs/user/cli.rst
- docs/user/installation.rst
- ignis/cli.py
- ignis/main.py
- nix/default.nix
- pyproject.toml
- requirements.txt
This PR moves CLI to using `typer` instead of `click`.
`typer` is nicer to use, provides a more beautiful help messages and has built-in completion support.
Also, it improves the CLI page in docs by making it autogenerated via [sphinxcontrib-typer](https://github.com/sphinx-contrib/typer) and adding description for each command.
- **Some commands were renamed in order to provide a more appropriate name:**
- `open` -> `open-window`
- `close` -> `close-window`
- `toggle` -> `toggle-window`
- **Ignis requires `typer` instead of `click` now**
> feat!(cli): move to `typer`

- docs/api/gobject.rst
- docs/api/index.rst
- docs/api/singleton.rst
- ignis/base_service.py
- ignis/gobject.py
- ignis/singleton.py
Adds separate ``IgnisSingleton`` and ``IgnisGObjectSingleton`` classes. Idk what to do with `BaseService`, let's leave it as is for now.
It's just a small step for #137...
> refactor: extract singleton logic into separate classes

- docs/api/index.rst
- docs/api/window_manager.rst
- docs/examples/code_snippets.rst
- ignis/app.py
- ignis/client.py
- ignis/services/network/access_point.py
- ignis/services/wallpaper/window.py
- ignis/widgets/regular_window.py
- ignis/widgets/window.py
- ignis/window_manager.py
This PR moves window management from `IgnisApp` to the new `WindowManager` class.
1. offload responsibilities from ``IgnisApp``
2. `IgnisApp.get_default()` currently guaranteed returns the instance, which causes problems implementing #137 because ``get_default()`` actually shouldn't initialize an instance. So `WindowManager` comes as the replacement.
The following methods and properties are deprecated, consider using the new ones:
- ``IgnisApp.windows`` -> ``WindowManager.windows``
- ``IgnisApp.get_window()`` -> ``WindowManager.get_window()``
- ``IgnisApp.add_window()`` -> ``WindowManager.add_window()``
- ``IgnisApp.remove_window()`` -> ``WindowManager.remove_window()``
- ``IgnisApp.open_window()`` -> ``WindowManager.open_window()``
- ``IgnisApp.close_window()`` -> …
> refactor!: extract window management into separate `WindowManager` class

- ignis/options.py
> fix: fallback `options.recorder.default_file_location` to $HOME if XDG dirs missing

- docs/api/icon_manager.rst
- docs/api/index.rst
- ignis/app.py
- ignis/icon_manager.py
This PR adds a new `IconManager` class to extend and replace the existing functionality provided by `IgnisApp.add_icons()`
`IgnisApp.add_icons()` is deprecated, use `IconManager.add_icons()` instead.
Replace this:
```python
from ignis import utils
from ignis.app import IgnisApp
app = IgnisApp.get_default()
app.add_icons(f"{utils.get_current_dir()}/icons")
```
with this:
```python
from ignis import utils
from ignis.icon_manager import IconManager
icon_manager = IconManager.get_default()
icon_manager.add_icons(f"{utils.get_current_dir()}/icons")
```
> feat!: add `IconManager`

- docs/api/utils/misc.rst
- ignis/_ignis_ipc.py
- ignis/app.py
- ignis/utils/__init__.py
- ignis/utils/misc.py
``IgnisApp.inspector()`` is deprecated, use ``utils.open_inspector()`` instead.
> chore!: move `IgnisApp.inspector()` to `utils`

- ignis/services/applications/application.py
> fix(`Application`): do not override `PATH` env var

- flake.nix
Otherwise, `venvShellHook` is not executed
> fix(nix): do not override `shellHook` in dev shell

- flake.nix
We have only one executable (bin) file and `nix run` works fine even without defining `apps` explicitly, so I don't see any points for keeping it.
> nix: remove definition of `apps`

- docs/user/nix.rst
- flake.nix
- nix/default.nix
- nix/devshell.nix
- nix/hm-module-doc.md
- nix/hm-module.nix
```nix
{
programs.ignis = {
enable = true;
addToPythonEnv = true;
configDir = ../ignis;
services = {
bluetooth.enable = true;
recorder.enable = true;
audio.enable = true;
network.enable = true;
};
sass = {
enable = true;
useDartSass = true;
};
extraPackages = with pkgs.python313Packages; [
jinja2
materialyoucolor
pillow
];
};
}
```
TODO:
> feat(nix): add Home Manager module

- docs/api/command_manager.rst
- docs/api/index.rst
- ignis/_ignis_ipc.py
- ignis/cli.py
- ignis/client.py
- ignis/command_manager.py
- ignis/dbus/com.github.linkfrg.ignis.xml
- ignis/exceptions.py
Closes: #315.
- Added class `CommandManager` to register custom commands.
- Added _DBus_ methods `ListCommands` and `RunCommand` to query and run custom commands.
- Added subcommands `list-commands` and `run-command` to `ignis` _CLI_.
A custom command is in form `def cmd(args: list[str]) -> str | None`:
- Run `ignis run-command echo foo bar`, a callback registered as `add_command("echo", lambda args: " ".join(args))` gives the output `foo bar`.
- Run `ignis run-command ping` and a callback registered as `add_command("ping", lambda _: "pong")` prints `pong`.
> feat: allow running custom commands from CLI

- ignis/services/hyprland/service.py
Not sure if this was done correctly but all this change does add a case for fullscreen and sync the active window.
As a side note, fullscreen does not return any address value just a single value the fullscreen state of the window.
closes: https://github.com/ignis-sh/ignis/issues/398
> feat(HyprlandService): support `fullscreen` event

- ignis/services/upower/service.py
Removes the strong requirement of running UPower during `UPowerService` initialization.
Now there is `is_available` property which represents whether UPower is running or not. However accessing `display_device` will still raise the exception.
> chore!(UPowerService): do not raise `UPowerNotRunningError` on init

- docs/api/widgets/Corner.rst
- ignis/widgets/__init__.py
- ignis/widgets/corner.py
Adds Corner Widget, can be used as screencorners or as corners to a widget
Code formatted using ruff,docstrings written by claude
Preview and usecase: 
Closes: #200
> feat: add `Corner` widget
